my_color = input("Enter a color:")
my_pluralnoun = input("Enter a plural noun:")
my_celebrity = input("Enter a celebrity:")
print("Roses are " + my_color)
print(my_pluralnoun + " are blue")
print("I love " + my_celebrity)